### ISSUE TITLE
You will be working on your experience on IBM in Data Science Fundamentals

### ISSUE THREAD

**Issue by TsheziM** [grouptoo/Team2#4]

**Comment by blackbad12y** [comment]
With IBM in data science fundamentals we where able to learn many skills and about data science and be able to understand  what is Big Data, types of data, Data Science tools, and the Data Science Life Cycle (CRISP-DM).

All members did demonstrate the following skills
analytics,Bigdata,machine learning,data science,unsupervised learning and etc
